name: Go Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Tidy
        run: go mod tidy

      - name: Verify build
        run: go build ./...

      - name: Run tests (unit only)
        run: go test ./... -count=1 -race -timeout=10m
